version: "2.4"

volumes:
  code-server:
  caddy_data:
  caddy_config:

services:
  code-server:
    build: ./code-server
    container_name: code-server
    network_mode: host
    privileged: true
    environment:
      - PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - DOCKER_MODS=linuxserver/mods:code-server-zsh|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-nvm|linuxserver/mods:universal-docker-in-docker
      - SHELL=/usr/bin/zsh
    volumes:
      - "code-server:/config"
    restart: unless-stopped
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-socket: 1
    command: --auth none --disable-telemetry

  caddy:
    build:
      context: ./caddy
      args:
      - DNS_PROVIDER=digitalocean
      - CADDY_VERSION=v2.5.2
    environment:
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/data
      - CADDY_VERSION=v2.5.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
