version: "2"
services:
  code-server:
    build: ./code-server
    container_name: code-server
    network_mode: host
    environment:
      - PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - DOCKER_MODS=linuxserver/mods:code-server-zsh
      - SHELL=/usr/bin/zsh
    volumes:
      - "appdata:/config"
    restart: unless-stopped
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
volumes:
  appdata: