version: "2"
services:
  code-server:
    build: ./code-server
    container_name: code-server
    network_mode: host
    privileged: true
    environment:
      - PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - DOCKER_MODS=linuxserver/mods:code-server-zsh|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-nvm|linuxserver/mods:universal-docker-in-docker
      - SHELL=/usr/bin/zsh
    volumes:
      - "code-server:/config"
    restart: unless-stopped
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-socket: 1
    cap_add:
      - CAP_NET_BIND_SERVICE # to allow port 80 binding
volumes:
  code-server: