#!/bin/bash

## Sam Dennon // June2024

# Define fonts and URLs
fonts=("VictorMono" "OperatorMono")
font_urls=(
  "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/VictorMono.zip"
  "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/OperatorMono.zip"
)

# Define font directory
font_dir="$HOME/.local/share/fonts"

# Check font directory
if [ ! -d "$font_dir" ]; then
  # Create directory if it doesn't exist
  mkdir -p "$font_dir"
fi

# Loop through fonts and URLs
for (( i=0; i<${#fonts[@]}; i++ )); do
  font_name="${fonts[$i]}"
  font_url="${font_urls[$i]}"

  # Check if font already exists
  if fc-list | grep -q "file:${font_dir}/${font_name}"; then
    echo "${font_name} Nerd Font already installed."
  else
    echo "Downloading and installing ${font_name} Nerd Font..."
    wget -qO- "$font_url" | unzip -q -d "$font_dir"
    fc-cache -fv
    echo "${font_name} Nerd Font installed!"
  fi
done