#!/usr/bin/with-contenv bash

if [ -e /config/.zshrc ]
then
  echo "Add NVM path to .zshrc"
  sed -ie '$a # NVM Path' /config/.zshrc
  sed -ie '$a export NVM_DIR=~/.nvm' /config/.zshrc
  sed -ie '$a [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' /config/.zshrc
else
  echo "No config needed, zsh is not installed"
fi